/* Export the shipped HELP_DOC to the Dropbox Guides folder.
   ---------------------------------------------------------------------------
   The guide people actually read is the HELP_DOC constant in index.html. This
   writes a plain-markdown copy for reading outside the app, so the two cannot
   drift: regenerate, never hand-edit the .md.

   Run after any HELP_DOC change (doc-currency rule 5):   node export-guide.js
*/
const fs = require("fs");
const path = require("path");

const SRC = path.join(__dirname, "index.html");
const OUT = "C:/Users/cjgra/Dropbox/My AI/CG Apps/ToDos Tasks Projects Ideas/" +
            "ToDos Tasks Guides/PRIORITY-CAPTAIN-GUIDE.md";

const src = fs.readFileSync(SRC, "utf8");
const m = src.match(/const HELP_DOC = `([\s\S]*?)`;\n/);
if(!m){ console.error("HELP_DOC not found in index.html"); process.exit(1); }
const body = m[1];

const header =
  "<!-- EXPORT, NOT THE SOURCE. The guide people actually read is the HELP_DOC\n" +
  "     constant in tracker-app/index.html, rendered in the app under More > Guide.\n" +
  "     Regenerate with `node export-guide.js`; do not edit this file by hand. -->\n\n";

if(!fs.existsSync(path.dirname(OUT))){
  console.error("Destination folder missing: " + path.dirname(OUT));
  process.exit(1);
}
fs.writeFileSync(OUT, header + body, "utf8");
console.log("wrote " + OUT);
console.log("chars: " + body.length + ", sections: " + (body.match(/^## /gm)||[]).length);
